### ISSUE TITLE
Other feeds then News Feed are not parsed

### ISSUE THREAD

**Issue by pigucatalin** [vladootz/audillo#19]
Steps:
Make sure you have friends separated in various lists (Close friends, ... )
Make sure that updates from them appear only in the appropriate list feed
Open Audillo

Result:
the songs from those list feeds are not in the playlist

Expected:
The list feeds should be parsed also

**Comment by vladootz** [comment]
News feed is not in the Graph API anymore, I'm afraid groups will go too.
